// Minimal activation server (Node.js)
const express = require('express');
const crypto = require('crypto');
const nodemailer = require('nodemailer');
const bodyParser = require('body-parser');
const Database = require('better-sqlite3');

const DB = new Database('./papi.db');
DB.exec(`CREATE TABLE IF NOT EXISTS activations (email TEXT, code TEXT, app TEXT, verified INTEGER, created_at INTEGER)`);

const REPO_API_KEY = process.env.REPO_API_KEY; // generated by your key generator (admin)
if (!REPO_API_KEY) { console.error('Set REPO_API_KEY'); process.exit(1); }

const transporter = nodemailer.createTransport(process.env.SMTP_URL); // e.g. smtp://user:pass@smtp.example.com:587

const app = express();
app.use(bodyParser.json());

// Admin-only endpoint: optionally generate/rotate keys using existing generator (not implemented here)
app.post('/request-activation', async (req, res) => {
  const { email, appId } = req.body;
  if (!email || !appId) return res.status(400).send({ error: 'email, appId required' });

  const code = (Math.floor(100000 + Math.random() * 900000)).toString();
  const stmt = DB.prepare('INSERT INTO activations (email, code, app, verified, created_at) VALUES (?, ?, ?, 0, ?)').run(email, code, appId, Date.now());

  // send email
  await transporter.sendMail({
    from: process.env.EMAIL_FROM || 'no-reply@example.com',
    to: email,
    subject: `Your activation code for ${appId}`,
    text: `Your activation code is: ${code}`
  });

  return res.send({ ok: true });
});

app.post('/verify-code', (req, res) => {
  const { email, appId, code } = req.body;
  if (!email || !appId || !code) return res.status(400).send({ error: 'email, appId, code required' });

  const row = DB.prepare('SELECT * FROM activations WHERE email=? AND app=? AND code=? ORDER BY created_at DESC LIMIT 1').get(email, appId, code);
  if (!row) return res.status(400).send({ error: 'invalid code' });

  DB.prepare('UPDATE activations SET verified=1 WHERE email=? AND app=? AND code=?').run(email, appId, code);

  // Issue signed activation token (short-lived). Use HMAC with REPO_API_KEY
  const payload = JSON.stringify({ email, appId, issued: Date.now() });
  const sig = crypto.createHmac('sha256', REPO_API_KEY).update(payload).digest('hex');
  const token = Buffer.from(payload).toString('base64') + '.' + sig;
  return res.send({ token });
});

// Admin quick-activate: issues token for an email+app when authenticated with repo admin key
app.post('/admin/activate', (req, res) => {
  const adminKey = req.headers['x-repo-admin-key'] || (req.body && req.body.adminKey);
  if (!adminKey || adminKey !== REPO_API_KEY) return res.status(403).send({ error: 'admin auth required' });
  const { email, appId } = req.body || {};
  if (!email || !appId) return res.status(400).send({ error: 'email and appId required' });

  // Insert verified activation record
  DB.prepare('INSERT INTO activations (email, code, app, verified, created_at) VALUES (?, ?, ?, 1, ?)').run(email, 'ADMIN', appId, Date.now());

  // Issue token
  const payload = JSON.stringify({ email, appId, issued: Date.now(), admin: true });
  const sig = crypto.createHmac('sha256', REPO_API_KEY).update(payload).digest('hex');
  const token = Buffer.from(payload).toString('base64') + '.' + sig;
  return res.send({ token });
});

app.post('/check-token', (req, res) => {
  const { token } = req.body;
  if (!token) return res.status(400).send({ error: 'token required' });
  const [b64, sig] = token.split('.');
  try {
    const payload = Buffer.from(b64, 'base64').toString('utf8');
    const expected = crypto.createHmac('sha256', REPO_API_KEY).update(payload).digest('hex');
    if (expected !== sig) return res.status(403).send({ valid: false });
    return res.send({ valid: true, payload: JSON.parse(payload) });
  } catch (e) {
    return res.status(400).send({ error: 'invalid token' });
  }
});

app.listen(3000, () => console.log('papi central running on :3000'));